### ISSUE TITLE
Probleme d'installation démarrage 

### ISSUE THREAD

**Issue by jbbordas** [projetssd/kubeseed#22]
**Décrire le bug**
lorsque j'ai lancé l'installation, kebeseed dit que tout n'est pas pret sur ma machine et qu'il doit installer des compansant. je valide le tout et apres quelques seconde j'ai cette erreur:
`./seedbox.sh: line 93: python: command not found`
`/home/bbo/kubeseed/profile.sh: line 10: /home/bbo/seedbox//venv/ks/bin/activate: No such file or directory
ls: cannot access '/home/bbo/seedbox//venv/ks/lib': No such file or directory
/home/bbo/kubeseed/profile.sh: line 21: /home/bbo/seedbox//venv/ks/bin/activate: No such file or directory
/home/bbo/kubeseed/profile.sh: line 23: kubectl: command not found
/home/bbo/kubeseed/profile.sh: line 24: kubectl: command not found
 
  ██╗  ██╗██╗   ██╗██████╗ ███████╗███████╗███████╗███████╗██████╗ 
  ██║ ██╔╝██║   ██║██╔══██╗██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗
  █████╔╝ ██║   ██║██████╔╝█████╗  ███████╗█████╗  █████╗  ██║  ██║
  ██╔═██╗ ██║   ██║██╔══██╗██╔══╝  ╚════██║██╔══╝  ██╔══╝  ██║  ██║
  ██║  ██╗╚██████╔╝██████╔╝███████╗███████║███████╗███████╗██████╔╝
  ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝╚══════╝╚═════╝ 
KubeSeed - Author: Merrick
Debian GNU/Linux 11 (bullseye)Linux 5.10.0-12-amd64 x86_64 GNU/Linux - Uptime: up 1 week, 2 days, 17 hours, 38 minutes
=============================================
./seedbox.sh: line 93: python: command not found
bbo@ssd2:~/kubeseed$ 
`
Voila tout ce que j'ai à l'ecrant de ma console : 

**Comment le reproduire**
Prendre mon serveur et refaire? sinon je pense ne pas avoir python d'installer sur sa machine.

**Contexte**
Merci de lancer la commande **ks_get_system_info** et de coller son résultat ici :
Malheureusement je ne suis pas allé suffisament loin dans mon installation pour le lancer:

`~/kubeseed$ ks_get_system_info
-bash: ks_get_system_info: command not found
`

le souccis est peut etre que la commande python n'existe pas sur ma version :
`~/kubeseed$ python
-bash: python: command not found`

Cependant j'ai celle la :
`python3 --version
Python 3.9.2`

**Comment by jbbordas** [comment]
Pour corriger j'ai effectuer cette commande:
`sudo ln -s /usr/bin/python3 /usr/bin/python`

peut etre un pre-requis a ajouter?

**Comment by Merrick28** [comment]
Salut, c'est à moi, je dois remplacer tous les python par python3

**Comment by Merrick28** [comment]
Closed by https://github.com/projetssd/kubeseed/commit/b4e3ac76f63660b98aa26bde33fcf57bfac90d29
