### ISSUE TITLE
Proble au lancement

### ISSUE THREAD

**Issue by jbbordas** [projetssd/kubeseed#23]
**Décrire le bug**
durant le début de l'installation lorsque l'on doit attendre quelques minutes le script s'arrette

**Comment le reproduire**

**Contexte**
voila ce que j'ai à l'écran:

`home/bbo/kubeseed/profile.sh: line 10: /home/bbo/seedbox//venv/ks/bin/activate: No such file or directory
ls: cannot access '/home/bbo/seedbox//venv/ks/lib': No such file or directory
/home/bbo/kubeseed/profile.sh: line 21: /home/bbo/seedbox//venv/ks/bin/activate: No such file or directory
/home/bbo/kubeseed/profile.sh: line 23: kubectl: command not found
/home/bbo/kubeseed/profile.sh: line 24: kubectl: command not found
 
  ██╗  ██╗██╗   ██╗██████╗ ███████╗███████╗███████╗███████╗██████╗ 
  ██║ ██╔╝██║   ██║██╔══██╗██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗
  █████╔╝ ██║   ██║██████╔╝█████╗  ███████╗█████╗  █████╗  ██║  ██║
  ██╔═██╗ ██║   ██║██╔══██╗██╔══╝  ╚════██║██╔══╝  ██╔══╝  ██║  ██║
  ██║  ██╗╚██████╔╝██████╔╝███████╗███████║███████╗███████╗██████╔╝
  ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝╚══════╝╚═════╝ 
KubeSeed - Author: Merrick
Debian GNU/Linux 11 (bullseye)Linux 5.10.0-23-amd64 x86_64 GNU/Linux - Uptime: up 21 hours, 29 minutes
=============================================
Traceback (most recent call last):
  File "/home/bbo/kubeseed/includes/scripts/menu.py", line 1, in <module>
    import kubeseed
  File "/home/bbo/kubeseed/includes/scripts/kubeseed.py", line 5, in <module>
    import inquirer
ModuleNotFoundError: No module named 'inquirer'
`

**Comment by Merrick28** [comment]
Closed by https://github.com/projetssd/kubeseed/commit/b4e3ac76f63660b98aa26bde33fcf57bfac90d29 (pas de détection de debian 11)
