### ISSUE TITLE
Bug d'affichage dans le menu - ajout d'application

### ISSUE THREAD

**Issue by kesurof** [projetssd/kubeseed#27]
![image](https://github.com/projetssd/kubeseed/assets/64525827/fadfc5f7-c1f5-4298-8708-0dab4174e3b7)

lorsque je clique sur la flèche bas, une ligne en haut `[?] Select applications to install:` ce rajoute
de plus il est impossible de sortir avec la touche échap, je suis obligé de faire CTRL C ce qui génère une autre erreur 

```
Cancelled by user

Traceback (most recent call last):
  File "/home/kesurof/kubeseed/includes/scripts/generique_python.py", line 9, in <module>
    eval('kubeseed.' + sys.argv[1] + '()')
  File "<string>", line 1, in <module>
  File "/home/kesurof/kubeseed/includes/scripts/kubeseed.py", line 80, in choix_appli_lance
    lance_applis(inquirer.prompt(questions)['applications'])
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Press any key to continue...
```

**Comment by Merrick28** [comment]
Pour la sortie, il faut faire "entrée" sans rien sélectionner. Je vais voir comment contourner le ctrl + c

Pour la ligne qui s'ajoute, je n'ai jamais eu ça, je vais essayer de reproduire

**Comment by kesurof** [comment]
> j'ai eu le cas avec Mobaxterm sur un premier PC sans raison particulière, j'ai ensuite essayé avec Mobaxterm sur un second et la aucun problème le menu fonctionnait correctement cependant j'ai fait échap pour en sortir.
> 
> j'ai essayé avec Tabby sur les deux PC et j'ai le même problème

j'ai eu le cas avec Mobaxterm sur un premier PC sans raison particulière, j'ai ensuite essayé avec Mobaxterm sur un second et la aucun problème le menu fonctionnait correctement cependant j'ai fait échap pour en sortir.

j'ai essayé avec Tabby sur les deux PC et j'ai le même problème

**Comment by kesurof** [comment]
> Pour la sortie, il faut faire "entrée" sans rien sélectionner. Je vais voir comment contourner le ctrl + c
> 
> Pour la ligne qui s'ajoute, je n'ai jamais eu ça, je vais essayer de reproduire

j'ai eu le cas avec Mobaxterm sur un premier PC sans raison particulière, j'ai ensuite essayé avec Mobaxterm sur un second et la aucun problème le menu fonctionnait correctement cependant j'ai fait échap pour en sortir.

j'ai essayé avec Tabby sur les deux PC et j'ai le même problème

**Comment by Merrick28** [comment]
Probleme trouvé : certaines descriptions d'applis sont trop longues et ça gère mal le retours à la ligne. J'ai raccourci celles qui posaient problème, et le bug dépendait de la largeur d'écran

**Comment by kesurof** [comment]
> Probleme trouvé : certaines descriptions d'applis sont trop longues et ça gère mal le retours à la ligne. J'ai raccourci celles qui posaient problème, et le bug dépendait de la largeur d'écran

Parfait 👍🏻

**Comment by Merrick28** [comment]
Le ctrl c devrait être ok

**Comment by kesurof** [comment]
> Le ctrl c devrait être ok

je confirme cela fonctionne correctement
```

Cancelled by user

Aucune application sélectionnée
Press any key to continue...
```
