### ISSUE TITLE
Suggestion - Création d'un raccourci pour lancer le menu 

### ISSUE THREAD

**Issue by kesurof** [projetssd/kubeseed#28]
**Suggestion** 

Comme sur SSDV2, ajouter la possibilité de simplement taper `seedbox` pour lancer le menu.

plutôt que devoir faire `cd "/home/$USER/kubeseed/" && ./seedbox.sh`

**Comment by Merrick28** [comment]
ajouté par commit https://github.com/projetssd/kubeseed/commit/fb8d40d668fcb9a63d9534fcdd84aa851b1bfce0

**Comment by kesurof** [comment]
> ajouté par commit [fb8d40d](https://github.com/projetssd/kubeseed/commit/fb8d40d668fcb9a63d9534fcdd84aa851b1bfce0)

il manque dans le menu l'équivalent de `9) Installation environnement
` afin de pouvoir taper directement `seedbox`

**Comment by Merrick28** [comment]
C'est fait par défaut, on n'a pas le choix avec kubeseed
