### ISSUE TITLE
Installation Oauth 2.0 Google

### ISSUE THREAD

**Issue by kesurof** [projetssd/kubeseed#29]
Après avoir vérifier les réglages côté Google il y a malgré tout une erreur concernant oAuth

```
Erreur 400 : redirect_uri_mismatch

Vous ne pouvez pas vous connecter à cette appli, car elle ne respecte pas le règlement OAuth 2.0 de Google.

Si vous êtes le développeur de l'appli, enregistrez l'URI de redirection dans la console Google Cloud.
Détails de la requête : redirect_uri=https://oauth.ndd.tld/oauth
```

**Comment by Merrick28** [comment]
C'est un problème dans la conf de google, il faut lui donner les url sur lesquelles tu peux revenir. Tu dois mettre

https://oauth.ndd.fr/_oauth

Pour autoriser cette url de retour, sans quoi gogole va bloquer (voir le wiki ssdv2 sur comment accéder/modifier les api google)

**Comment by kesurof** [comment]
> C'est un problème dans la conf de google, il faut lui donner les url sur lesquelles tu peux revenir. Tu dois mettre
> 
> https://oauth.ndd.fr/_oauth
> 
> Pour autoriser cette url de retour, sans quoi gogole va bloquer (voir le wiki ssdv2 sur comment accéder/modifier les api google)

C'est déjà le cas, j'ai simplement remplacer mon véritable ndd par ndd.tld

**Comment by kesurof** [comment]
> C'est un problème dans la conf de google, il faut lui donner les url sur lesquelles tu peux revenir. Tu dois mettre
> 
> https://oauth.ndd.fr/_oauth
> 
> Pour autoriser cette url de retour, sans quoi gogole va bloquer (voir le wiki ssdv2 sur comment accéder/modifier les api google)

C'est déjà le cas, j'ai simplement remplacé mon véritable ndd par ndd.tld

**Comment by Merrick28** [comment]
L'url de retour doit être https://oauth.ndd.fr/oauth
