### ISSUE TITLE
Suggestion - Taguer les apps qui n'ont pas de gui

### ISSUE THREAD

**Issue by kesurof** [projetssd/kubeseed#31]
Afin de ne pas avoir à gérer l'accès à la GUI des apps qui n'ont pas cette fonction, est ce qu'il serait possible d'ajouter un tag ?

![image](https://github.com/projetssd/kubeseed/assets/64525827/6353291a-3d5d-4336-a758-314ea5751a19)

Exemple d'apps à réinitialiser suite à l'installation de oAuth, alors que certaine d'entres elle n'ont pas de GUI

**Comment by Merrick28** [comment]
Fait par commit https://github.com/projetssd/kubeseed/commit/8f90af7527cdede0a2eae4eb529551eeee9d9c9e
Nécessite  que le tag no_gui soit présent dans le yml de définition de l'application
