### ISSUE TITLE
Suggestion ** 

### ISSUE THREAD

**Issue by kesurof** [projetssd/kubeseed#32]
Demande d'ajout de fonctionnalité rtorrent-cleaner

> rtorrent-cleaner de @Magicalex-Mondedie.fr

https://github.com/Magicalex/rtorrent-cleaner

**Comment by Merrick28** [comment]
rtorrent-cleaner ne peut pas s'installer en container dans kubeseed (déjà testé dans tous les sens). Le seul moyen de l'installer est d'installer le programme "en dur" sur la machine, et nécessite l'ajout de nombreuses bibliothèques (notamment php). Cela est hors cadre de kubeseed qui par défaut touche le moins possible au système.

**Comment by Merrick28** [comment]
https://github.com/projetssd/kubeseed/commit/c5df17aed0514e44aa0fc2266b5a7416066a55c4
